language: android

android:
  components:
    - platform-tools
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository,
    - extra-android-support
    - extra-google-gcm
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-intel-Hardware_Accelerated_Execution_Manager
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license-.+'
    - 'mips-android-sysimage-license-.+'

jdk:
  - oraclejdk8

before_script:
   #######################################
   #
   # Gradle
   #
   ######################################

   # Add gradle properties
   - touch $HOME/.gradle/gradle.properties
   # Disable gradle daemon
   - echo 'org.gradle.daemon=false' > $HOME/.gradle/gradle.properties

   #######################################
   #
   # Android SDK
   #
   ######################################
   - mkdir "$ANDROID_HOME/licenses" || true
   - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"

   #######################################
   #
   # Google Cloud SDK
   #
   ######################################
   - wget -q https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-138.0.0-linux-x86_64.tar.gz
   - tar xzf google-cloud-sdk-138.0.0-linux-x86_64.tar.gz
   - ./google-cloud-sdk/install.sh --usage-reporting=true --path-update=false --bash-completion=false --additional-components alpha beta gcloud
   - rm -rf google-cloud-sdk-138.0.0-linux-x86_64.tar.gz
   - ./google-cloud-sdk/bin/gcloud config set --installation component_manager/disable_update_check true

   #######################################
   #
   # Android NDK Setup
   #
   ######################################
   - wget -q https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
   - unzip -qo android-ndk-r12b-linux-x86_64.zip
   - export ANDROID_NDK_HOME="$HOME/android-ndk-r12b"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
  - git rev-parse HEAD
  - echo "$ANDROID_NDK_HOME"

deploy:
  provider:
    - script
  script:
    - git rev-parse HEAD
    - echo "$ANDROID_NDK_HOME"
  on:
    tags: true
